---
- name: "Install AWS cli dependency"
  apt:
    pkg:
      - curl
      - unzip
    update_cache: yes
    state: latest

- name: Download AWS CLI v2
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip

- name: Unzip AWS CLI package
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: yes

- name: Install or update AWS CLI
  command: /tmp/aws/install --update

- name: "Create AWS config dir"
  file:
    path: /root/.aws
    state: directory
    mode: '0750'

- name: "Create Backups dir"
  file:
    path: /opt/backups
    state: directory
    mode: '0750'

- name: "Create script dir"
  file:
    path: /opt/scripts
    state: directory
    mode: '0750'

- name: "Copy template AWS files - credentials"
  template:
    src: "credentials.j2"
    dest: "/root/.aws/credentials"
    owner: root
    group: root
    mode: '0600'

- name: "Copy template AWS files - config"
  template:
    src: "config.j2"
    dest: "/root/.aws/config"
    owner: root
    group: root
    mode: '0600'

- name: "Copy backup script"
  template:
    src: "backup.j2"
    dest: "/opt/scripts/backup.sh"
    owner: root
    group: root
    mode: '0750'

- name: "Create cronjob"
  cron:
    name: "Backup script for {{ aws_backup_db_name }}"
    minute: "{{ range(0, 59) | random }}"
    hour: "9"
    user: root
    job: '/bin/bash -c "/opt/scripts/backup.sh"'
